### PR TITLE
Experiment: adding an [nb_occurs] function.

### PR DESCRIPTION
**Pull request by rlepigre**
This is one possible way to address https://github.com/rlepigre/ocaml-bindlib/issues/29, but it is not clear this is what we want since it might impact performance. In particular, we introduce an extra pointer indirection since we cannot unbox the `anyvar` type anymore.

### CODE REVIEW

**Comment by craff** [comment]
If also does count very well in all cases: if you define

```
let self_app : term box -> term box =
  fun t -> box_apply (fun t -> App(t,t)) t
```
If will count variable in t only once. It is not clear what the user wants in such a case.

**Comment by rlepigre** [comment]
That's a good point, I guess this approach can only work if the argument of functions passed to `box_apply` and friends is always used linearly (which I think is pretty much always the case (?)).

In any case, this PR is really just an experiment, it is really not clear to me whether we want/need this.

**Comment by craff** [comment]
I can review the PR ... or we drop it ?

**Comment by rlepigre** [comment]
We should probably drop it at this point, given the problem you highlighted.

**Pull request closed without merging**
