### PR TITLE
Example of how to count variable occurrences

### PR DESCRIPTION
**Pull request by craff**
This add a new example `occur_count.ml` showing how to address issue #29.

### CODE REVIEW

**Comment by rlepigre** [comment]
This MR is definitely doing more than adding one example.

**Comment by craff** [comment]
It is on top of another MR. That was already approved... But not merged. I can redo it on top of master? 

Le 4 avril 2023 09:22:59 GMT-10:00, Rodolphe Lepigre ***@***.***> a écrit :

**Comment by rlepigre** [comment]
It is always better to work on top of master: I'm not sure what was happening in the other MR, and looking at what it contains I don't want to just merge it as is.

**Comment by craff** [comment]
Rodolphe Lepigre writes:

> It is always better to work on top of master: I'm not sure what was happening in the other MR, and looking at what it contains I don't want to just merge it as is.

Ok, I do antoher PR on top of master, when I have time too. Probably
tomorow. We could attache the file lambda_count.ml to the issue too?

I also completely forgot that MR! This is why I worked on top of it ;-)


--
Christophe Raffalli
tél: +689 87 23 11 48
web: http://raffalli.eu

Ce mail est signé avec pgp (Pièce jointe signature.asc, clef sur https://raffalli.eu/pgp)
This mail is signed pgp (Attachment signature.asc, clef on https://raffalli.eu/pgp)

**Comment by rlepigre** [comment]
OK, I fixed both your branches @craff. I think you can just do `git pull --rebase` to get you back into a good state. If that does not work you can always do `git reset --hard origin/more_examples` (and similar in the other branch).

**Comment by rlepigre** [comment]
Also, for some reason you create commits with someone else's name? Not sure how that happened.

**Comment by craff** [comment]
Rodolphe Lepigre writes:

> Also, for some reason you create commits with someone else's name? Not sure how that happened.

I don't understand, I have name=craff in my .git/config ?

I can not review PR#30, you did not ask for a review ?

Cheers,
Christophe


--
Christophe Raffalli
tél: +689 87 23 11 48
web: http://raffalli.eu

Ce mail est signé avec pgp (Pièce jointe signature.asc, clef sur https://raffalli.eu/pgp)
This mail is signed pgp (Attachment signature.asc, clef on https://raffalli.eu/pgp)

**Comment by craff** [comment]
Rodolphe Lepigre writes:

> OK, I fixed both your branches @craff. I think you can just do `git pull --rebase` to get you back into a good state. If that does not work you can always do `git reset --hard origin/more_examples` (and similar in the other branch).

Yep, it worked fine. the two branches corresponding the the PR are now
clean. Thanks for the work!!!

--
Christophe Raffalli
tél: +689 87 23 11 48
web: http://raffalli.eu

Ce mail est signé avec pgp (Pièce jointe signature.asc, clef sur https://raffalli.eu/pgp)
This mail is signed pgp (Attachment signature.asc, clef on https://raffalli.eu/pgp)

**Comment by craff** [comment]
On en est où avec cette PR ?

**Review by rlepigre — APPROVED** [review]
I cleaned up the example a bit (removed unnecessary parts duplicated from `examples/lambda.ml`), and edited your commits to fix the broken email you had in there.

I think we can merge this now.

**Pull request merged**
